spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/subscriptions
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/saas
          # Alternativa: jwk-set-uri: http://localhost:8082/realms/saas/protocol/openid-connect/certs

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    metrics:
      enabled: true
    info:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger

app:
  security:
    jwt:
      provider: keycloak # Pode ser 'keycloak' ou 'standard'
      keycloak:
        client-id: subscriptions-api
